# coding: utf-8

"""
    Simpplr APIs

    This collection of Simpplr APIs lets developers create and manage content outside the Simpplr UI. We have APIs for notifications, alerts, app searches, and content creation. Looking for parameters or code samples? Click on an endpoint to see a sample snippet along with descriptions of its parameters and responses.  If you have questions about an API, reach out to us support@simpplr.com  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.body14 import Body14  # noqa: E501
from swagger_client.rest import ApiException


class TestBody14(unittest.TestCase):
    """Body14 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody14(self):
        """Test Body14"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.body14.Body14()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
