# coding: utf-8

"""
    Simpplr APIs

    This collection of Simpplr APIs lets developers create and manage content outside the Simpplr UI. We have APIs for notifications, alerts, app searches, and content creation. Looking for parameters or code samples? Click on an endpoint to see a sample snippet along with descriptions of its parameters and responses.  If you have questions about an API, reach out to us support@simpplr.com  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.search_api import SearchApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self):
        self.api = SearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_content_search(self):
        """Test case for content_search

        Search a Content  # noqa: E501
        """
        pass

    def test_external_auto_complete(self):
        """Test case for external_auto_complete

        Auto Complete Search  # noqa: E501
        """
        pass

    def test_file_search(self):
        """Test case for file_search

        Search a File  # noqa: E501
        """
        pass

    def test_search_feed_posts(self):
        """Test case for search_feed_posts

        Search feed posts  # noqa: E501
        """
        pass

    def test_site_search(self):
        """Test case for site_search

        Search a Site  # noqa: E501
        """
        pass

    def test_top_search(self):
        """Test case for top_search

        Search a Top  # noqa: E501
        """
        pass

    def test_user_search(self):
        """Test case for user_search

        Search a User  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
