# coding: utf-8

"""
    Simpplr APIs

    This collection of Simpplr APIs lets developers create and manage content outside the Simpplr UI. We have APIs for notifications, alerts, app searches, and content creation. Looking for parameters or code samples? Click on an endpoint to see a sample snippet along with descriptions of its parameters and responses.  If you have questions about an API, reach out to us support@simpplr.com  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.site_api import SiteApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSiteApi(unittest.TestCase):
    """SiteApi unit test stubs"""

    def setUp(self):
        self.api = SiteApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_apex_data_server_r_wtarget_site_data_serveractiongetsite_detail_data_get(self):
        """Test case for apex_data_server_r_wtarget_site_data_serveractiongetsite_detail_data_get

        Get a Site  # noqa: E501
        """
        pass

    def test_site_activate_deactivate(self):
        """Test case for site_activate_deactivate

        Activate and Deactivate a Site  # noqa: E501
        """
        pass

    def test_site_add_follower(self):
        """Test case for site_add_follower

        Add Follower to Site  # noqa: E501
        """
        pass

    def test_site_add_member(self):
        """Test case for site_add_member

        Add Member to Site  # noqa: E501
        """
        pass

    def test_site_category(self):
        """Test case for site_category

        Search Site Category  # noqa: E501
        """
        pass

    def test_site_category_by_id(self):
        """Test case for site_category_by_id

        Search Site CategoryById  # noqa: E501
        """
        pass

    def test_site_create(self):
        """Test case for site_create

        Search Site  # noqa: E501
        """
        pass

    def test_site_create_0(self):
        """Test case for site_create_0

        Create a Site  # noqa: E501
        """
        pass

    def test_site_edit(self):
        """Test case for site_edit

        Edit Site Details  # noqa: E501
        """
        pass

    def test_site_featured(self):
        """Test case for site_featured

        Search Site Featured  # noqa: E501
        """
        pass

    def test_site_following(self):
        """Test case for site_following

        Search Following Site  # noqa: E501
        """
        pass

    def test_site_latest(self):
        """Test case for site_latest

        Search Site Latest  # noqa: E501
        """
        pass

    def test_site_member(self):
        """Test case for site_member

        Search Site Member  # noqa: E501
        """
        pass

    def test_site_mysite(self):
        """Test case for site_mysite

        Search Mysite  # noqa: E501
        """
        pass

    def test_site_popular(self):
        """Test case for site_popular

        Search Site Popular  # noqa: E501
        """
        pass

    def test_site_remove_follower(self):
        """Test case for site_remove_follower

        Remove Follower to Site  # noqa: E501
        """
        pass

    def test_site_remove_member(self):
        """Test case for site_remove_member

        Remove Member to Site  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
