# coding: utf-8

"""
    Simpplr APIs

    This collection of Simpplr APIs lets developers create and manage content outside the Simpplr UI. We have APIs for notifications, alerts, app searches, and content creation. Looking for parameters or code samples? Click on an endpoint to see a sample snippet along with descriptions of its parameters and responses.  If you have questions about an API, reach out to us support@simpplr.com  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.content_api import ContentApi  # noqa: E501
from swagger_client.rest import ApiException


class TestContentApi(unittest.TestCase):
    """ContentApi unit test stubs"""

    def setUp(self):
        self.api = ContentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_event_create(self):
        """Test case for event_create

        Create an Event  # noqa: E501
        """
        pass

    def test_event_delete(self):
        """Test case for event_delete

        Delete an Event  # noqa: E501
        """
        pass

    def test_event_get(self):
        """Test case for event_get

        Get an Event  # noqa: E501
        """
        pass

    def test_event_update(self):
        """Test case for event_update

        Update an Event  # noqa: E501
        """
        pass

    def test_list_latest_content_for_a_site_by_site_id(self):
        """Test case for list_latest_content_for_a_site_by_site_id

        List Latest Content for a site by Site ID  # noqa: E501
        """
        pass

    def test_list_latest_contentfromsites_ifollow(self):
        """Test case for list_latest_contentfromsites_ifollow

        List Latest Content from sites I follow  # noqa: E501
        """
        pass

    def test_list_popular_content_for_a_site_by_site_id(self):
        """Test case for list_popular_content_for_a_site_by_site_id

        List Popular Content for a site by Site ID  # noqa: E501
        """
        pass

    def test_page_create(self):
        """Test case for page_create

        Create a Page  # noqa: E501
        """
        pass

    def test_page_delete(self):
        """Test case for page_delete

        Delete a Page  # noqa: E501
        """
        pass

    def test_page_get(self):
        """Test case for page_get

        Get a Page  # noqa: E501
        """
        pass

    def test_page_update(self):
        """Test case for page_update

        Edit a Page  # noqa: E501
        """
        pass

    def test_search_content_from_sites_i_follow(self):
        """Test case for search_content_from_sites_i_follow

        List popular Content from sites I follow  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
