# coding: utf-8

"""
    Simpplr APIs

    This collection of Simpplr APIs lets developers create and manage content outside the Simpplr UI. We have APIs for notifications, alerts, app searches, and content creation. Looking for parameters or code samples? Click on an endpoint to see a sample snippet along with descriptions of its parameters and responses.  If you have questions about an API, reach out to us support@simpplr.com  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.blog_api import BlogApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBlogApi(unittest.TestCase):
    """BlogApi unit test stubs"""

    def setUp(self):
        self.api = BlogApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_blog_create(self):
        """Test case for blog_create

        Create a Blog  # noqa: E501
        """
        pass

    def test_blog_delete(self):
        """Test case for blog_delete

        Delete a Blog  # noqa: E501
        """
        pass

    def test_blog_get(self):
        """Test case for blog_get

        Get a Blog  # noqa: E501
        """
        pass

    def test_blog_update(self):
        """Test case for blog_update

        Update a Blog  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
