# coding: utf-8

"""
    Simpplr APIs

    This collection of Simpplr APIs lets developers create and manage content outside the Simpplr UI. We have APIs for notifications, alerts, app searches, and content creation. Looking for parameters or code samples? Click on an endpoint to see a sample snippet along with descriptions of its parameters and responses.  If you have questions about an API, reach out to us support@simpplr.com  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.people_api import PeopleApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPeopleApi(unittest.TestCase):
    """PeopleApi unit test stubs"""

    def setUp(self):
        self.api = PeopleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_profile_by_people_id(self):
        """Test case for get_profile_by_people_id

        Get profile by People Id  # noqa: E501
        """
        pass

    def test_get_profile_by_user_id(self):
        """Test case for get_profile_by_user_id

        Get profile by User Id  # noqa: E501
        """
        pass

    def test_list_people(self):
        """Test case for list_people

        List People  # noqa: E501
        """
        pass

    def test_list_people_by_expertise(self):
        """Test case for list_people_by_expertise

        List people by Expertise  # noqa: E501
        """
        pass

    def test_list_people_in_my_department(self):
        """Test case for list_people_in_my_department

        List people in my department  # noqa: E501
        """
        pass

    def test_list_people_in_my_location(self):
        """Test case for list_people_in_my_location

        List people in my location  # noqa: E501
        """
        pass

    def test_people_update(self):
        """Test case for people_update

        Edit profile by people Id  # noqa: E501
        """
        pass

    def test_search(self):
        """Test case for search

        Search  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
