# coding: utf-8

"""
    Simpplr APIs

    This collection of Simpplr APIs lets developers create and manage content outside the Simpplr UI. We have APIs for notifications, alerts, app searches, and content creation. Looking for parameters or code samples? Click on an endpoint to see a sample snippet along with descriptions of its parameters and responses.  If you have questions about an API, reach out to us support@simpplr.com  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SiteCategoryById(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'size': 'int',
        'category': 'str',
        'sort_by': 'str'
    }

    attribute_map = {
        'size': 'size',
        'category': 'category',
        'sort_by': 'sortBy'
    }

    def __init__(self, size=None, category=None, sort_by=None):  # noqa: E501
        """SiteCategoryById - a model defined in Swagger"""  # noqa: E501
        self._size = None
        self._category = None
        self._sort_by = None
        self.discriminator = None
        if size is not None:
            self.size = size
        if category is not None:
            self.category = category
        if sort_by is not None:
            self.sort_by = sort_by

    @property
    def size(self):
        """Gets the size of this SiteCategoryById.  # noqa: E501


        :return: The size of this SiteCategoryById.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this SiteCategoryById.


        :param size: The size of this SiteCategoryById.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def category(self):
        """Gets the category of this SiteCategoryById.  # noqa: E501


        :return: The category of this SiteCategoryById.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this SiteCategoryById.


        :param category: The category of this SiteCategoryById.  # noqa: E501
        :type: str
        """

        self._category = category

    @property
    def sort_by(self):
        """Gets the sort_by of this SiteCategoryById.  # noqa: E501


        :return: The sort_by of this SiteCategoryById.  # noqa: E501
        :rtype: str
        """
        return self._sort_by

    @sort_by.setter
    def sort_by(self, sort_by):
        """Sets the sort_by of this SiteCategoryById.


        :param sort_by: The sort_by of this SiteCategoryById.  # noqa: E501
        :type: str
        """

        self._sort_by = sort_by

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SiteCategoryById, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SiteCategoryById):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
